### ISSUE TITLE
[BUG] Failed drawing interface canvas group

### ISSUE THREAD

**Issue by mathamel** [ironmonk88/monks-active-tiles#855]
**Describe the bug**
After upgrading to lastest Foundryvtt and Monk's Active Tiles, all scenes now throw this error and cannot be rendered. Even scenes without any tiles.
Failed drawing interface canvas group: Framebuffer width or height is zero [Detected 1 package: monks-active-tiles(12.02)]

**To Reproduce**
1. Have a world with the module active
2. Migrate the world from v9 to v12
3. Open any scene

**Expected behavior**
Scene should load without issue.

When I deactivate the module, everything loads normally.

**Screenshots**

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/b77132e7-f996-4868-aa29-a625dd49c358">
<img width="647" alt="image" src="https://github.com/user-attachments/assets/e9f55e29-5b54-4d88-a194-b2ba213c47e4">

**Please complete as much of the following information as possible:**
 - Browser [chrome]
 - Foundry Version [v12]
 - System [Dungeon World]
 - Module version 12.02
 - Are there any errors in the console [e.g. press F12 and look for red text]
foundry.js:655 Error: Failed drawing interface canvas group: Framebuffer width or height is zero. Framebuffer width or height is zero
[Detected 1 package: monks-active-tiles(12.02)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #draw (foundry.js:25064:15)
    at async Canvas.draw (foundry.js:24948:5)
    at async Scene.view (foundry.js:21369:7)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
  Yes, the issue is there even with only this module active.

**Additional context**

**Comment by Roymitch** [comment]
I have also encountered the same bug after updating to v12, though I had updated from v11. 

In my testing I found that once I opened a scene which was having this issue, it would cause all scenes to fail to load until I reloaded the webpage.

I found that I could replicate this with any scene where I created a tile with the following settings:
- Tile image uses a blank image (I was using modules/monks-active-tiles/img/1x1.png)

![Image](https://github.com/user-attachments/assets/90739a71-0e87-45b9-9b20-12e1621899c4)

- The trigger option "trigger using image instead of boarder" must be checked.

![Image](https://github.com/user-attachments/assets/816a42a8-2c80-4360-bad1-0ed4fab36b60)

- Everything else can be default

When I then navigate away from the scene and back, I would get the Framebuffer error.

Browser Firefox
Foundry Version v12 build 331
System D&D 5e v4.3.5
Module version 12.02
